/**
 * Stable, language-neutral error codes used across HTTP, Socket.IO, and CLI/Agent.
 * Codes are uppercase snake_case and never renamed once published (wire contract).
 * Add new codes append-only; do not reuse retired numbers.
 */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  /** Frozen student-search query validation code. */
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVER_SHUTTING_DOWN: 'SERVER_SHUTTING_DOWN',

  // Auth (Phase 2)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_STEP_UP_REQUIRED: 'AUTH_STEP_UP_REQUIRED',
  AUTH_PASSWORD_CHANGE_REQUIRED: 'AUTH_PASSWORD_CHANGE_REQUIRED',
  AUTH_CSRF_INVALID: 'AUTH_CSRF_INVALID',
  AUTH_RATE_LIMIT_UNAVAILABLE: 'AUTH_RATE_LIMIT_UNAVAILABLE',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',

  // Domain
  COURSE_ARCHIVED: 'COURSE_ARCHIVED',
  COURSE_NOT_EDITABLE: 'COURSE_NOT_EDITABLE',
  SESSION_NOT_JOINABLE: 'SESSION_NOT_JOINABLE',
  ENROLLMENT_REQUIRED: 'ENROLLMENT_REQUIRED',
  ENROLLMENT_REMOVED: 'ENROLLMENT_REMOVED',
  SUBMISSION_CONFLICT: 'SUBMISSION_CONFLICT',
  QUESTION_TYPE_INVALID: 'QUESTION_TYPE_INVALID',
  SELECTION_MODE_INVALID: 'SELECTION_MODE_INVALID',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  FIELD_FORBIDDEN: 'FIELD_FORBIDDEN',
  TEXT_EMPTY: 'TEXT_EMPTY',
  TEXT_TOO_LONG: 'TEXT_TOO_LONG',
  TEXT_UNSAFE: 'TEXT_UNSAFE',
  OPTION_COUNT_INVALID: 'OPTION_COUNT_INVALID',
  OPTION_DUPLICATE: 'OPTION_DUPLICATE',
  OPTION_REF_INVALID: 'OPTION_REF_INVALID',
  CORRECT_OPTION_INVALID: 'CORRECT_OPTION_INVALID',
  QUESTION_LOCKED_BY_SESSION: 'QUESTION_LOCKED_BY_SESSION',
  BATCH_SIZE_INVALID: 'BATCH_SIZE_INVALID',
  CLIENT_REF_DUPLICATE: 'CLIENT_REF_DUPLICATE',
  VALIDATION_TOKEN_INVALID: 'VALIDATION_TOKEN_INVALID',
  VALIDATION_TOKEN_EXPIRED: 'VALIDATION_TOKEN_EXPIRED',
  VALIDATION_TOKEN_CONSUMED: 'VALIDATION_TOKEN_CONSUMED',
  PAYLOAD_HASH_MISMATCH: 'PAYLOAD_HASH_MISMATCH',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  CLI_CREDENTIAL_INVALID: 'CLI_CREDENTIAL_INVALID',
  CLI_CREDENTIAL_REVOKED: 'CLI_CREDENTIAL_REVOKED',
  RESULTS_NOT_REVEALED: 'RESULTS_NOT_REVEALED',
  SESSION_QUESTION_NOT_OPEN: 'SESSION_QUESTION_NOT_OPEN',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
