-- Migration: init_system_setting
-- Phase 1 baseline. Establishes the additive-migration convention:
--   * Identity: UUID v7 generated by the application (no DB default) — see
--     M2 關鍵技術決策 §1. PK type is UUID.
--   * Status columns use TEXT + CHECK, written by hand in later migrations
--     (Prisma cannot emit CHECK constraints).
--   * Partial unique indexes and advisory-lock consumers are added by hand
--     with `prisma migrate dev --create-only` + manual SQL in Phase 2+.
-- This migration is additive only (single new table); safe to deploy before
-- any read/write path exists.

-- CreateTable
CREATE TABLE "system_setting" (
    "id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "system_setting_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "system_setting_key_key" ON "system_setting"("key");