#!/usr/bin/env bash
set -euo pipefail

# Disposable MinIO rehearsal RUNNER for BE-5.2 / Checkpoint G step 3.
#
# Sources the write-only credentials generated by setup.sh (gitignored), keeps
# NODE_ENV=test so the DB comes from .env.test, and runs the guarded S3 sandbox
# integration spec. The spec exercises: conditional immutable write
# (If-None-Match:'*', ChecksumSHA256, COMPLIANCE object retention), exact replay
# equality, outbox -> exported, idempotent replay, and duplicate re-put accepted.
#
# Read-back verification (GetObject/HeadObject/retention headers) is NOT
# performed here because the write-only credential cannot read back; the provider
# treats a conflict-verification 403 as idempotent success (see
# src/modules/governance/application/s3-manifest.provider.ts) and this is the
# documented intent. A separate admin verification step is optional and requires
# an admin credential you must supply explicitly.
#
# Requires: a running Docker daemon + MinIO provisioned by setup.sh.
#
# Usage:  ops/minio-rehearsal/rehearse.sh  [--only <jestName>]

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND="$(cd "${ROOT}/../.." && pwd)"
ENV_IN="${ROOT}/.env.minio-rehearsal"

if [ ! -f "${ENV_IN}" ]; then
  echo "[rehearse] ERROR: ${ENV_IN} not found. Run ops/minio-rehearsal/setup.sh first." >&2
  exit 1
fi

# Load ONLY the S3 credential vars (never print them); the DB url stays from
# .env.test via NODE_ENV=test. Explicit allowlist so unrelated vars cannot leak
# in from the minio env file.
set -a
# shellcheck disable=SC1090
source <(grep -E '^(DELETION_MANIFEST_PROVIDER|S3_)[A-Z_]*[=]' "${ENV_IN}")
set +a

cd "${BACKEND}"
export NODE_ENV=test

JEST_NAME="${1:+-t \"$1\"}"

echo "[rehearse] provider=${DELETION_MANIFEST_PROVIDER} endpoint=${S3_ENDPOINT} bucket=${S3_BUCKET}"
echo "[rehearse] running guarded sandbox integration spec..."
# shellcheck disable=SC2086
if [ -n "${1:-}" ]; then
  npm run test:integration -- --runInBand --silent test/s3-sandbox-rehearsal.integration-spec.ts -t "$1"
else
  npm run test:integration -- --runInBand --silent test/s3-sandbox-rehearsal.integration-spec.ts
fi

echo "[rehearse] PASS — upload rehearsal green against disposable MinIO."
echo "[rehearse] Optionally verify object retention/checksum with an ADMIN credential:"
echo "          mc stat local/${S3_BUCKET}/${S3_PREFIX}/<eventId>.json"
echo "[rehearse] Tear down when done:  ops/minio-rehearsal/teardown.sh"
