#!/usr/bin/env bash
set -euo pipefail

# Disposable MinIO rehearsal setup for BE-5.2 / Checkpoint G step 3.
#
# Creates the object-lock + versioning-enabled bucket and a prefix-scoped
# write-only user for the DELETE-manifest upload path. App-generated credentials
# are written ONLY to the gitignored ops/minio-rehearsal/.env.minio-rehearsal
# file (never printed, never committed); the operator sources it into the
# rehearsal env (see rehearse.sh).
#
# Requires: a running Docker daemon with the compose plugin, and the MinIO client
# `mc`. `mc` is bootstrapped from inside the running container below so no host
# install is needed.
#
# Usage:  ops/minio-rehearsal/setup.sh
# Then:   ops/minio-rehearsal/rehearse.sh

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTAINER="minio-rehearsal-minio-1"
BUCKET="sl-rehearsal-manifests"
PREFIX="deletion-manifests"
REGION="us-east-1"
ENDPOINT="http://127.0.0.1:19000"
ENV_OUT="${ROOT}/.env.minio-rehearsal"

REHEARSAL_ROOT_USER="${MINIO_ROOT_USER:-rehearsal-root}"
REHEARSAL_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-rehearsal-write-password-1234}"

# Throwaway local sandbox creds; the write-only user that the app uses is
# generated fresh each setup (never the root key).
ACCESS_KEY_PREFIX="rehearsal-upload"

mc() { docker exec --env MC_HOST_local="${REHEARSAL_ROOT_USER}:${REHEARSAL_ROOT_PASSWORD}@http://127.0.0.1:19000" "${CONTAINER}" /usr/bin/mc "$@"; }

echo "[setup] waiting for MinIO at ${ENDPOINT} ..."
for i in $(seq 1 60); do
  if docker exec "${CONTAINER}" /usr/bin/mc ready local >/dev/null 2>&1; then break; fi
  [ "$i" -eq 60 ] && { echo "[setup] ERROR: MinIO did not become ready" >&2; exit 1; }
  sleep 1
done

echo "[setup] creating bucket ${BUCKET} with object-lock + versioning..."
mc mb                                        \
  --with-lock                                 \
  --region "${REGION}"                        \
  "local/${BUCKET}"
mc version enable "local/${BUCKET}"

echo "[setup] creating prefix-scoped write-only user..."
ACCESS_KEY="$(printf '%s-%s' "${ACCESS_KEY_PREFIX}" "$(head -c 6 /dev/urandom | od -An -tx1 | tr -d ' \n')")"
SECRET_KEY="$(head -c 24 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=')"

# Policy: PutObject + ListBucket + HeadObject/GetBucketObjectLockConfiguration on
# the prefix only. HeadObject is needed so a re-put that hits PreconditionFailed
# can verify the existing object (provider read-back path). No delete.
cat > "${ROOT}/.policy-rehearsal-write.json" <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:PutObject"],
      "Resource": ["arn:aws:s3:::${BUCKET}/${PREFIX}/*"]
    },
    {
      "Effect": "Allow",
      "Action": ["s3:HeadObject"],
      "Resource": ["arn:aws:s3:::${BUCKET}/${PREFIX}/*"]
    },
    {
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": ["arn:aws:s3:::${BUCKET}"]
    }
  ]
}
POLICY
mc admin user add "local" "${ACCESS_KEY}" "${SECRET_KEY}"
mc admin policy create "local" rehearsal-write "${ROOT}/.policy-rehearsal-write.json"
mc admin policy attach "local" rehearsal-write --user "${ACCESS_KEY}"
rm -f "${ROOT}/.policy-rehearsal-write.json"

cat > "${ENV_OUT}" <<ENVFILE
# Generated by ops/minio-rehearsal/setup.sh $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Sources into the rehearsal env. DO NOT COMMIT — gitignored.
DELETION_MANIFEST_PROVIDER=s3
S3_ENDPOINT=${ENDPOINT}
S3_REGION=${REGION}
S3_BUCKET=${BUCKET}
S3_PREFIX=${PREFIX}
S3_ACCESS_KEY_ID=${ACCESS_KEY}
S3_SECRET_ACCESS_KEY=${SECRET_KEY}
S3_OBJECT_LOCK_DAYS=90
S3_SERVER_SIDE_ENCRYPTION=none
ENVFILE
chmod 600 "${ENV_OUT}"

echo "[setup] OK — bucket + write-only user ready."
echo "[setup] Credentials written to ${ENV_OUT} (gitignored; values never printed)."
echo "[setup] Next:  ops/minio-rehearsal/rehearse.sh"
