#!/usr/bin/env bash
set -euo pipefail

# Disposable MinIO rehearsal setup for BE-5.2 / Checkpoint G step 3.
#
# Creates the object-lock + versioning-enabled bucket and a prefix-scoped
# write-only user for the DELETE-manifest upload path. App-generated credentials
# are written ONLY to the gitignored ops/minio-rehearsal/.env.minio-rehearsal
# file (never printed, never committed); the operator sources it into the
# rehearsal env (see rehearse.sh).
#
# Requires: a running Docker daemon with the compose plugin, and the MinIO client
# `mc`. `mc` is bootstrapped from inside the running container below so no host
# install is needed.
#
# Usage:  ops/minio-rehearsal/setup.sh
# Then:   ops/minio-rehearsal/rehearse.sh

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTAINER="minio-rehearsal-minio-1"
BUCKET="sl-rehearsal-manifests"
PREFIX="deletion-manifests"
REGION="us-east-1"
ENDPOINT="http://127.0.0.1:19000"
ENV_OUT="${ROOT}/.env.minio-rehearsal"

REHEARSAL_ROOT_USER="${MINIO_ROOT_USER:-rehearsal-root}"
REHEARSAL_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-rehearsal-write-password-1234}"

# Throwaway local sandbox creds; the write-only user that the app uses is
# generated fresh each setup (never the root key).
ACCESS_KEY_PREFIX="rehearsal-upload"

# NOTE: MC_HOST_ env form is overridden by the image's baked-in
# /tmp/.mc/config.json in newer mc builds, so we set an explicit alias with a
# private MC_CONFIG_DIR instead (idempotent for every mc call below).
mc() {
  docker exec -e MC_CONFIG_DIR=/tmp/.mc-rehearsal "${CONTAINER}" /usr/bin/mc \
    alias set local "http://127.0.0.1:19000" "${REHEARSAL_ROOT_USER}" "${REHEARSAL_ROOT_PASSWORD}" >/dev/null 2>&1
  docker exec -e MC_CONFIG_DIR=/tmp/.mc-rehearsal "${CONTAINER}" /usr/bin/mc "$@"
}

echo "[setup] waiting for MinIO at ${ENDPOINT} ..."
for i in $(seq 1 60); do
  if docker exec -e MC_CONFIG_DIR=/tmp/.mc-rehearsal "${CONTAINER}" /usr/bin/mc \
       alias set local "http://127.0.0.1:19000" "${REHEARSAL_ROOT_USER}" "${REHEARSAL_ROOT_PASSWORD}" >/dev/null 2>&1 \
    && docker exec -e MC_CONFIG_DIR=/tmp/.mc-rehearsal "${CONTAINER}" /usr/bin/mc ready local >/dev/null 2>&1; then break; fi
  [ "$i" -eq 60 ] && { echo "[setup] ERROR: MinIO did not become ready" >&2; exit 1; }
  sleep 1
done

echo "[setup] creating bucket ${BUCKET} with object-lock + versioning..."
if ! mc stat "local/${BUCKET}" >/dev/null 2>&1; then
  mc mb --with-lock --region "${REGION}" "local/${BUCKET}"
else
  echo "[setup] bucket ${BUCKET} already exists — skipping mb"
fi
mc version enable "local/${BUCKET}"

echo "[setup] creating prefix-scoped write-only user..."
ACCESS_KEY="$(printf '%s-%s' "${ACCESS_KEY_PREFIX}" "$(head -c 6 /dev/urandom | od -An -tx1 | tr -d ' \n')")"
# Pad with a leading letter so the secret can never start with '-' (this mc
# build parses a leading dash as a flag and does not honor '--' on admin user add).
SECRET_KEY="k$(head -c 24 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=')"

# Policy: PutObject + PutObjectRetention (per-object COMPLIANCE dates need it
# on MinIO) + ListBucket, plus GetObject so the provider's replay verification
# HeadObject is authorized (MinIO has no s3:HeadObject action; Head falls under
# s3:GetObject). Manifest bodies are deletion evidence, not secrets, and the
# provider only reads metadata/length — never the body. No delete.
cat > "${ROOT}/.policy-rehearsal-write.json" <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:PutObject", "s3:PutObjectRetention", "s3:GetObject"],
      "Resource": ["arn:aws:s3:::${BUCKET}/${PREFIX}/*"]
    },
    {
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": ["arn:aws:s3:::${BUCKET}"]
    }
  ]
}
POLICY
mc admin user add "local" "${ACCESS_KEY}" "${SECRET_KEY}"
docker cp "${ROOT}/.policy-rehearsal-write.json" "${CONTAINER}:/tmp/policy.json"
mc admin policy create "local" rehearsal-write /tmp/policy.json
mc admin policy attach "local" rehearsal-write --user "${ACCESS_KEY}"
docker exec "${CONTAINER}" rm -f /tmp/policy.json
rm -f "${ROOT}/.policy-rehearsal-write.json"

cat > "${ENV_OUT}" <<ENVFILE
# Generated by ops/minio-rehearsal/setup.sh $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Sources into the rehearsal env. DO NOT COMMIT — gitignored.
DELETION_MANIFEST_PROVIDER=s3
S3_ENDPOINT=${ENDPOINT}
S3_REGION=${REGION}
S3_BUCKET=${BUCKET}
S3_PREFIX=${PREFIX}
S3_ACCESS_KEY_ID=${ACCESS_KEY}
S3_SECRET_ACCESS_KEY=${SECRET_KEY}
S3_OBJECT_LOCK_DAYS=90
S3_SERVER_SIDE_ENCRYPTION=none
ENVFILE
chmod 600 "${ENV_OUT}"

echo "[setup] OK — bucket + write-only user ready."
echo "[setup] Credentials written to ${ENV_OUT} (gitignored; values never printed)."
echo "[setup] Next:  ops/minio-rehearsal/rehearse.sh"
