-- BE-5.2: durable retention purge claim/retry state.
-- Additive only. There is no down migration; disable/forward-fix is the rollback path.
-- UUID v7 lease tokens are generated by the application layer in a later checkpoint.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "archived_result"
    WHERE ("status" = 'active' AND "payload" IS NULL)
       OR ("status" = 'deleted' AND "payload" IS NOT NULL)
  ) THEN
    RAISE EXCEPTION 'archive status/payload invariant violated before purge-state migration';
  END IF;
  -- purgeAt is never moved or rewritten by this migration; its closedAt + 90 days
  -- provenance is an application invariant (archiveSessionInTransaction) and is not
  -- a migration preflight. Backfill sets next_purge_attempt_at from purge_at as-is.
END $$;

ALTER TABLE "archived_result"
  ADD COLUMN "purge_state" TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN "purge_attempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "next_purge_attempt_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "purge_lease_token" UUID,
  ADD COLUMN "purge_lease_expires_at" TIMESTAMPTZ,
  ADD COLUMN "last_purge_failure_code" TEXT,
  ADD COLUMN "last_purge_failed_at" TIMESTAMPTZ,
  ADD COLUMN "quarantined_at" TIMESTAMPTZ;

UPDATE "archived_result"
SET "purge_state" = CASE
      WHEN "status" = 'deleted' THEN 'deleted'
      ELSE 'pending'
    END,
    "purge_attempts" = 0,
    "next_purge_attempt_at" = "purge_at",
    "purge_lease_token" = NULL,
    "purge_lease_expires_at" = NULL,
    "last_purge_failure_code" = NULL,
    "last_purge_failed_at" = NULL,
    "quarantined_at" = NULL;

ALTER TABLE "archived_result"
  ADD CONSTRAINT "ck_archived_result_purge_state"
    CHECK ("purge_state" IN ('pending', 'processing', 'retry', 'quarantined', 'deleted')),
  ADD CONSTRAINT "ck_archived_result_purge_attempts_nonnegative"
    CHECK ("purge_attempts" >= 0),
  ADD CONSTRAINT "ck_archived_result_purge_failure_code"
    CHECK (
      "last_purge_failure_code" IS NULL
      OR "last_purge_failure_code" IN (
        'invariant_conflict',
        'fk_blocker',
        'lease_lost',
        'transient_db',
        'unavailable_db',
        'unknown'
      )
    ),
  ADD CONSTRAINT "ck_archived_result_purge_failure_pair"
    CHECK (
      ("last_purge_failure_code" IS NULL) = ("last_purge_failed_at" IS NULL)
    ),
  ADD CONSTRAINT "ck_archived_result_purge_state_coherence"
    CHECK (
      (
        "status" = 'active'
        AND "payload" IS NOT NULL
        AND "purge_state" IN ('pending', 'retry')
        AND "purge_lease_token" IS NULL
        AND "purge_lease_expires_at" IS NULL
        AND "quarantined_at" IS NULL
      )
      OR (
        "status" = 'active'
        AND "payload" IS NOT NULL
        AND "purge_state" = 'processing'
        AND "purge_lease_token" IS NOT NULL
        AND "purge_lease_expires_at" IS NOT NULL
        AND "quarantined_at" IS NULL
      )
      OR (
        "status" = 'active'
        AND "payload" IS NOT NULL
        AND "purge_state" = 'quarantined'
        AND "purge_lease_token" IS NULL
        AND "purge_lease_expires_at" IS NULL
        AND "quarantined_at" IS NOT NULL
      )
      OR (
        "status" = 'deleted'
        AND "payload" IS NULL
        AND "purge_state" = 'deleted'
        AND "purge_lease_token" IS NULL
        AND "purge_lease_expires_at" IS NULL
        AND "quarantined_at" IS NULL
      )
    );

-- Partial index for oldest-first due work and expired processing-lease recovery.
CREATE INDEX "idx_archived_result_purge_work"
  ON "archived_result" (
    "purge_at",
    "id",
    "next_purge_attempt_at",
    "purge_lease_expires_at"
  )
  WHERE "status" = 'active'
    AND "purge_state" IN ('pending', 'retry', 'processing');
