-- Migration: add_poll_live_session_submission
-- Minimal persisted vertical slice: poll/single Question -> LiveSession -> Participant -> Submission.
-- Additive only; UUID v7 values are generated by the application layer.
-- State values use TEXT + CHECK per M2 decisions. PostgreSQL remains the authority.

-- QuestionDefinition ------------------------------------------------------
CREATE TABLE "question_definition" (
    "id" UUID NOT NULL,
    "course_id" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "prompt" TEXT NOT NULL,
    "selection_mode" TEXT,
    "position" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "question_definition_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "question_definition_type_check"
      CHECK ("type" IN ('poll', 'open_text', 'quiz')),
    CONSTRAINT "question_definition_prompt_length_check"
      CHECK (char_length("prompt") BETWEEN 1 AND 1000),
    CONSTRAINT "question_definition_selection_check"
      CHECK (
        ("type" = 'poll' AND "selection_mode" IN ('single', 'multiple'))
        OR ("type" IN ('open_text', 'quiz') AND "selection_mode" IS NULL)
      ),
    CONSTRAINT "question_definition_position_check" CHECK ("position" > 0),
    CONSTRAINT "question_definition_course_id_fkey"
      FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "uq_question_definition_course_position"
  ON "question_definition"("course_id", "position");
CREATE INDEX "idx_question_definition_course"
  ON "question_definition"("course_id");

-- QuestionOption ----------------------------------------------------------
CREATE TABLE "question_option" (
    "id" UUID NOT NULL,
    "question_definition_id" UUID NOT NULL,
    "text" TEXT NOT NULL,
    "is_correct" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER NOT NULL,

    CONSTRAINT "question_option_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "question_option_text_length_check"
      CHECK (char_length("text") BETWEEN 1 AND 250),
    CONSTRAINT "question_option_position_check" CHECK ("position" > 0),
    CONSTRAINT "question_option_question_definition_id_fkey"
      FOREIGN KEY ("question_definition_id")
      REFERENCES "question_definition"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "uq_question_option_question_position"
  ON "question_option"("question_definition_id", "position");
CREATE INDEX "idx_question_option_question_position"
  ON "question_option"("question_definition_id", "position");

-- LiveSession -------------------------------------------------------------
CREATE TABLE "live_session" (
    "id" UUID NOT NULL,
    "course_id" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'waiting',
    "session_code" TEXT NOT NULL,
    "started_at" TIMESTAMPTZ,
    "closed_at" TIMESTAMPTZ,
    "auto_closed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "live_session_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "live_session_status_check"
      CHECK ("status" IN ('waiting', 'active', 'closed', 'cancelled')),
    CONSTRAINT "live_session_code_check"
      CHECK ("session_code" ~ '^[A-HJ-NP-Z2-9]{8}$'),
    CONSTRAINT "live_session_course_id_fkey"
      FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "live_session_session_code_key"
  ON "live_session"("session_code");
CREATE UNIQUE INDEX "uq_live_session_course_open"
  ON "live_session"("course_id") WHERE "status" IN ('waiting', 'active');
CREATE INDEX "idx_live_session_course"
  ON "live_session"("course_id");

-- LiveSessionQuestionSelection --------------------------------------------
CREATE TABLE "live_session_question_selection" (
    "id" UUID NOT NULL,
    "live_session_id" UUID NOT NULL,
    "question_definition_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,

    CONSTRAINT "live_session_question_selection_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "live_session_question_selection_position_check" CHECK ("position" > 0),
    CONSTRAINT "live_session_question_selection_live_session_id_fkey"
      FOREIGN KEY ("live_session_id") REFERENCES "live_session"("id") ON DELETE CASCADE,
    CONSTRAINT "live_session_question_selection_question_definition_id_fkey"
      FOREIGN KEY ("question_definition_id")
      REFERENCES "question_definition"("id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "uq_live_session_selection_session_position"
  ON "live_session_question_selection"("live_session_id", "position");
CREATE UNIQUE INDEX "uq_live_session_selection_question"
  ON "live_session_question_selection"("live_session_id", "question_definition_id");
CREATE INDEX "idx_live_session_selection_session_position"
  ON "live_session_question_selection"("live_session_id", "position");

-- SessionQuestion ---------------------------------------------------------
CREATE TABLE "session_question" (
    "id" UUID NOT NULL,
    "live_session_id" UUID NOT NULL,
    "question_definition_id" UUID,
    "position" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'not_open',
    "snapshot_type" TEXT NOT NULL,
    "snapshot_prompt" TEXT NOT NULL,
    "snapshot_selection_mode" TEXT,
    "opened_at" TIMESTAMPTZ,
    "closed_at" TIMESTAMPTZ,

    CONSTRAINT "session_question_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "session_question_status_check"
      CHECK ("status" IN ('not_open', 'open', 'closed')),
    CONSTRAINT "session_question_type_check"
      CHECK ("snapshot_type" IN ('poll', 'open_text', 'quiz')),
    CONSTRAINT "session_question_prompt_length_check"
      CHECK (char_length("snapshot_prompt") BETWEEN 1 AND 1000),
    CONSTRAINT "session_question_position_check" CHECK ("position" > 0),
    CONSTRAINT "session_question_live_session_id_fkey"
      FOREIGN KEY ("live_session_id") REFERENCES "live_session"("id") ON DELETE RESTRICT,
    CONSTRAINT "session_question_question_definition_id_fkey"
      FOREIGN KEY ("question_definition_id")
      REFERENCES "question_definition"("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "uq_session_question_session_position"
  ON "session_question"("live_session_id", "position");
CREATE UNIQUE INDEX "uq_session_question_one_open"
  ON "session_question"("live_session_id") WHERE "status" = 'open';
CREATE INDEX "idx_session_question_session_position"
  ON "session_question"("live_session_id", "position");

-- SessionQuestionOption ---------------------------------------------------
CREATE TABLE "session_question_option" (
    "id" UUID NOT NULL,
    "session_question_id" UUID NOT NULL,
    "text" TEXT NOT NULL,
    "is_correct" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER NOT NULL,

    CONSTRAINT "session_question_option_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "session_question_option_text_length_check"
      CHECK (char_length("text") BETWEEN 1 AND 250),
    CONSTRAINT "session_question_option_position_check" CHECK ("position" > 0),
    CONSTRAINT "session_question_option_session_question_id_fkey"
      FOREIGN KEY ("session_question_id")
      REFERENCES "session_question"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "uq_session_question_option_question_position"
  ON "session_question_option"("session_question_id", "position");
CREATE INDEX "idx_session_question_option_question_position"
  ON "session_question_option"("session_question_id", "position");

-- Participant -------------------------------------------------------------
CREATE TABLE "participant" (
    "id" UUID NOT NULL,
    "live_session_id" UUID NOT NULL,
    "display_name" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "joined_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "participant_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "participant_display_name_length_check"
      CHECK (char_length("display_name") BETWEEN 1 AND 40),
    CONSTRAINT "participant_live_session_id_fkey"
      FOREIGN KEY ("live_session_id") REFERENCES "live_session"("id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "uq_participant_session_token_hash"
  ON "participant"("live_session_id", "token_hash");
CREATE INDEX "idx_participant_session_token_hash"
  ON "participant"("live_session_id", "token_hash");

-- Submission --------------------------------------------------------------
CREATE TABLE "submission" (
    "id" UUID NOT NULL,
    "live_session_id" UUID NOT NULL,
    "session_question_id" UUID NOT NULL,
    "participant_id" UUID NOT NULL,
    "idempotency_key" UUID NOT NULL,
    "selected_option_refs" JSONB,
    "text_answer" TEXT,
    "submitted_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "submission_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "submission_selected_option_refs_array_check"
      CHECK (
        "selected_option_refs" IS NULL
        OR jsonb_typeof("selected_option_refs") = 'array'
      ),
    CONSTRAINT "submission_live_session_id_fkey"
      FOREIGN KEY ("live_session_id") REFERENCES "live_session"("id") ON DELETE RESTRICT,
    CONSTRAINT "submission_session_question_id_fkey"
      FOREIGN KEY ("session_question_id") REFERENCES "session_question"("id") ON DELETE RESTRICT,
    CONSTRAINT "submission_participant_id_fkey"
      FOREIGN KEY ("participant_id") REFERENCES "participant"("id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "submission_idempotency_key_key"
  ON "submission"("idempotency_key");
CREATE UNIQUE INDEX "uq_submission_participant_question"
  ON "submission"("participant_id", "session_question_id");
CREATE INDEX "idx_submission_session_question"
  ON "submission"("session_question_id");
CREATE INDEX "idx_submission_live_session"
  ON "submission"("live_session_id");
