-- Migration: add_cli_credential_and_batch
-- Q-4: CLI credential subsystem + batch question validate/confirm.
-- Additive only; UUID v7 values are generated by the application layer.
-- State values use TEXT + CHECK per M2 decisions. PostgreSQL remains the authority.
-- This lands the `cli_credential` deferred in migration 20260815174233.

-- CliCredential ----------------------------------------------------------
CREATE TABLE "cli_credential" (
    "id" UUID NOT NULL,
    "account_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "key_hash" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT 'all_courses',
    "status" TEXT NOT NULL DEFAULT 'active',
    "last_used_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ,

    CONSTRAINT "cli_credential_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "cli_credential_status_check"
      CHECK ("status" IN ('active', 'revoked')),
    CONSTRAINT "cli_credential_scope_check"
      CHECK ("scope" IN ('all_courses', 'single_course')),
    CONSTRAINT "cli_credential_name_length_check"
      CHECK (char_length("name") BETWEEN 1 AND 64),
    CONSTRAINT "cli_credential_account_id_fkey"
      FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "uq_cli_credential_account_name"
  ON "cli_credential"("account_id", "name");
CREATE UNIQUE INDEX "cli_credential_key_hash_key"
  ON "cli_credential"("key_hash");
CREATE INDEX "idx_cli_credential_account"
  ON "cli_credential"("account_id");

-- QuestionValidationToken ------------------------------------------------
CREATE TABLE "question_validation_token" (
    "id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "account_id" UUID NOT NULL,
    "cli_credential_id" UUID,
    "course_id" UUID NOT NULL,
    "payload_hash" TEXT NOT NULL,
    "schema_version" INTEGER NOT NULL DEFAULT 1,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "consumed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "question_validation_token_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "question_validation_token_account_id_fkey"
      FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE,
    CONSTRAINT "question_validation_token_cli_credential_id_fkey"
      FOREIGN KEY ("cli_credential_id") REFERENCES "cli_credential"("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "question_validation_token_token_hash_key"
  ON "question_validation_token"("token_hash");
CREATE INDEX "idx_validation_token_account_course"
  ON "question_validation_token"("account_id", "course_id");

-- QuestionBatchIdempotency ------------------------------------------------
CREATE TABLE "question_batch_idempotency" (
    "id" UUID NOT NULL,
    "actor_scope" TEXT NOT NULL,
    "operation" TEXT NOT NULL DEFAULT 'question-batch-confirm',
    "idempotency_key" TEXT NOT NULL,
    "payload_hash" TEXT NOT NULL,
    "response_json" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "question_batch_idempotency_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "uq_batch_idempotency_actor_op_key"
  ON "question_batch_idempotency"("actor_scope", "operation", "idempotency_key");
CREATE INDEX "idx_batch_idempotency_actor_key"
  ON "question_batch_idempotency"("actor_scope", "idempotency_key");