-- Migration: add_cli_credential_rotation_lineage
-- BE-8.3 CP3: immediate CLI key rotation with retained predecessor lineage.
-- Additive only; UUID v7 values are generated by the application layer.
-- No CLI expiry, grace-period, pending, or version state is introduced.

ALTER TABLE "cli_credential"
  ADD COLUMN "rotated_from_id" UUID;

ALTER TABLE "cli_credential"
  ADD CONSTRAINT "cli_credential_rotated_from_id_fkey"
  FOREIGN KEY ("rotated_from_id")
  REFERENCES "cli_credential"("id")
  ON DELETE SET NULL
  ON UPDATE NO ACTION;

CREATE UNIQUE INDEX "uq_cli_credential_rotated_from"
  ON "cli_credential"("rotated_from_id");
